# Generated by Django 6.0.2 on 2026-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintmedia',
            name='file_url',
        ),
        migrations.AddField(
            model_name='complaintmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
