# Generated by Django 6.0.2 on 2026-02-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaintmedia_file_url_complaintmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sla_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='urgency_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
