# Generated by Django 6.0.2 on 2026-02-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_sla_days_complaint_urgency_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AI_PROCESSED', 'AI Processed'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
    ]
